// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"
import "../controllers"
import "@hotwired/turbo-rails"
import HelloController from "./hello_controller"
import CountryController from "./country_controller"
application.register("hello", HelloController)
application.register("country", CountryController)
