version: '3'

services:
  web: &app_base
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      REDIS_URL_CACHING: redis://redis:6379/0
      REDIS_URL_SIDEKIQ: redis://redis:6379/1

    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        APP_DIR: /home/user/myapp

    command: bash -c "rm -f tmp/pids/server.pid &&
                      ./bin/webpack-dev-server &
                      bundle exec rails server -p 3000 -b '0.0.0.0'"

    volumes:
      # make sure this lines up with APP_DIR above
      - .:/home/user/myapp

    ports:
      - "3000:3000"
      - '3035:3035'

    depends_on:
      - 'db'
      - 'redis'

  db:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6381:6381'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/home/user/myapp'
    env_file:
      - '.env'

  worker:
    <<: *app_base
    command: "sidekiq -C config/initializers/sidekiq.yml"
    entrypoint: []
    deploy:
      resources:
        limits:
          cpus: '${DOCKER_WORKER_CPUS:-0}'
          memory: '${DOCKER_WORKER_MEMORY:-0}'

    ports: []
    depends_on:
      - web

volumes:
  redis:
  db_data:
